---

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/kub/amira
    state: directory
    mode: '0755'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '666'
  become_method: sudo

- name: Log into DockerHub
  docker_login:
    username: AAguech
    password: Lasmar.eline2021
    email: amira.aguech.lasmar@gmail.com
  run_once: true


- name: pull an image
  docker_image:
    name: hello-world
    pull: yes

#- name: Tag and push to local registry
 # docker_image:
  #   name: alpine/helm
   #  repository: /home/kub/amira/helm
   #  tag: latest
   #  push: yes

- name: log to jfrog 
  docker_login:
    registry: firstproject.jfrog.io/hello-world/docker-amira-local
    #registry: sncf.jfrog.io/docker-amira-local 
    username: amir2aguech@gmail.com
    password: Lasmar.eline2021

#- name : tag image with command before to push it
 # command: docker tag hello-world:latest hello-word:v1

- name: Build an image and push it to a private repo
  docker_image:
    name: hello-world
    repository: firstproject.jfrog.io/hello-world/docker-amira-local/hello-world
    #repository: sncf.jfrog.io/docker-amira-local/hello-world
    push: yes
    