---
#creat helm_work_directory
helm_work_directory: /home/amira/projet-helm-k8s/demo-helm

artifactory_url: https://firstproject.jfrog.io/ui/repos/tree/General

artifactory_repository: demoChart
project_name: demoChart

artifactory_username: amir2aguech@gmail.com
artifactory_password: Lasmar.eline2021