---
- name: Create work directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "{{ helm_work_directory }}/old"
    - "{{ helm_work_directory }}/new"

- name: get the original index file
  get_url:
      url: "{{ artifactory_url }}/{{ artifactory_repository }}/index.yaml"
      dest: "{{ helm_work_directory }}/old/index.yaml"
      mode: 0755
      backup: yes
      validate_certs: true
      force: true
  no_log: "{{ no_debug | default(true) }}"
  ignore_errors: true

- name: Package charts
  command: "helm package {{ project_name }}/ --destination new/"
  args:
    chdir: "{{ helm_work_directory }}"

- name: Index charts
  command: "helm repo index --merge old/index.yaml new/ --url {{ artifactory_url }}/{{ artifactory_repository }}"
  args:
    chdir: "{{ helm_work_directory }}"

- name: get files
  find:
    paths: "{{ helm_work_directory }}/new"
    file_type: "file"
  register: find_result

- name : debug find_resultat test
  debug:
    var: find_result


- name: Pushing all files to artifactory
  uri:
    url: "{{ artifactory_url }}/{{ artifactory_repository }}/{{ item.path | basename }}"
    method: PUT
    remote_src: yes
    return_content: yes
    status_code: 201
    src: "{{ item.path }}"
    user: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"
   # headers:
    #  X-JFrog-Art-Api: "{{ artifactory_api_key }}"
  with_items:
      - "{{ find_result.files }}"


- name: Cleanup work directory
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ helm_work_directory }}/old"
    - "{{ helm_work_directory }}/new"