---
- hosts: minikube-machine
  roles:
    - role: install-helmChart
      vars:
        extra_params:
          image.repository: "{{ docker_repo }}/{{ app_name }}"
          image.tag: "{{ selected_version }}"
          serviceAccount.create : "{{ is_created }}"
